### ISSUE TITLE
Question -- Does this plugin work on unreal engine 5?

### ISSUE THREAD

**Issue by german-cantu** [getnamo/TensorFlow-Unreal#70]
I am developing a video game with voice recognition I want to use a LSTM network and I want to know if this plugin works for unreal engine 5 ? , thank you.

**Comment by getnamo** [comment]
There's a 5.0 and 5.1 release: https://github.com/getnamo/TensorFlow-Unreal/releases

The API now uses the machine learning remote architecture, see https://github.com/getnamo/MachineLearningRemote-Unreal

**Comment by german-cantu** [comment]
Thank you i'm working at the moment with ONNX but i will check it more latter.
